// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDsGZS2WszY2loQpmOvC6HRYRj8EEpph0',
    appId: '1:471341674678:web:13be639a5daf7b3bf43617',
    messagingSenderId: '471341674678',
    projectId: 'travil-68915',
    authDomain: 'travil-68915.firebaseapp.com',
    storageBucket: 'travil-68915.firebasestorage.app',
    measurementId: 'G-WDY1B0X2WN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2KLFZM-8YM8qCnt15_GNHefrQEldCPXA',
    appId: '1:471341674678:android:a878dd187f9da3aef43617',
    messagingSenderId: '471341674678',
    projectId: 'travil-68915',
    storageBucket: 'travil-68915.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx-g8Ncpybmh2cbiRGblYJOVOWiXwtG8A',
    appId: '1:471341674678:ios:e211dccbd5677a4cf43617',
    messagingSenderId: '471341674678',
    projectId: 'travil-68915',
    storageBucket: 'travil-68915.firebasestorage.app',
    androidClientId: '471341674678-31pqvsd0gj0ig19tj1kup2i8tg0t8hn1.apps.googleusercontent.com',
    iosClientId: '471341674678-t80ui0ti8gf4aelfjiqh3a9g4h575cgk.apps.googleusercontent.com',
    iosBundleId: 'com.example.travil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx-g8Ncpybmh2cbiRGblYJOVOWiXwtG8A',
    appId: '1:471341674678:ios:e211dccbd5677a4cf43617',
    messagingSenderId: '471341674678',
    projectId: 'travil-68915',
    storageBucket: 'travil-68915.firebasestorage.app',
    androidClientId: '471341674678-31pqvsd0gj0ig19tj1kup2i8tg0t8hn1.apps.googleusercontent.com',
    iosClientId: '471341674678-t80ui0ti8gf4aelfjiqh3a9g4h575cgk.apps.googleusercontent.com',
    iosBundleId: 'com.example.travil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDsGZS2WszY2loQpmOvC6HRYRj8EEpph0',
    appId: '1:471341674678:web:2de34445eb0b3376f43617',
    messagingSenderId: '471341674678',
    projectId: 'travil-68915',
    authDomain: 'travil-68915.firebaseapp.com',
    storageBucket: 'travil-68915.firebasestorage.app',
    measurementId: 'G-2K66Q8ZZDK',
  );
}
